name: Build Repo Listing

on: 
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-listing:
    name: build-listing
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # setup environment 
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      # checkout repository
      - uses: actions/checkout@v3

      # build the listing
      - name: Build Listing
        run: deno run --allow-write=dist --allow-read=dist,src,creator creator/main.ts
 
      # deploy pages
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
